import{S as L,i as c,a as y}from"./assets/vendor-c145bea9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const v=document.querySelector(".form"),i=document.querySelector(".loader-top"),m=document.querySelector(".loader-bottom"),d=document.querySelector(".gallery"),n=document.querySelector(".load-image");let l=1,p="cat",g=40;const f=new L(".gallery a",{captionsData:"alt",captionDelay:250,nav:!0,close:!0,enableKeyboard:!0,docClose:!0});v.addEventListener("submit",w);n.addEventListener("click",S);async function w(r){if(r.preventDefault(),i.style.display="block",n.style.display="none",l=1,p=r.target.elements.search.value.trim(),!p){d.innerHTML="",c.info({position:"topRight",message:"Error enter any symbols"}),i.style.display="none";return}try{const{data:{hits:s,totalHits:t}}=await h(p,l);s.length>0?(i.style.display="none",d.innerHTML=b(s),f.refresh(),c.success({position:"topRight",message:`We found ${t} photos`}),n.style.display="block"):(d.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=g&&(n.style.display="none")}catch{console.log("Error")}finally{i.style.display="none",r.target.reset()}}function h(r,s){return y.defaults.baseURL="https://pixabay.com",y.get("/api/",{params:{key:"34228101-50b55348103eeb6dd10b59f8d",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:40}})}function b(r=[]){return r.reduce((s,t)=>s+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function S(r){m.style.display="block",loadImg.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{l+=1;const{data:{hits:a,totalHits:e}}=await h(p,l),o=Math.ceil(e/g);if(n.style.display="block",d.insertAdjacentHTML("beforeend",b(a)),f.refresh(),l===o)return n.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(a){console.log(a)}finally{m.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
